### DISCUSSION TITLE
WARNING! The Fast API branch will be merged into master soon

### DISCUSSION THREAD

**Discussion by I-am-PUID-0** [I-am-PUID-0/DMB#98] [Announcements]
Below is the initial post on Discord detailing Fast API

The day has come; I will push the latest release to the FastAPI branch in its current form!

Documentation has not yet been updated, so some key pieces of information are below. 

1. Do not update until you READ below! ‼️
2. DMB functions have been majorly overhauled. The addition of the dmb_config.json has changed the names of most, if not all, previous environment variables. See the .env.example file on the repo. 👀
3. Parts of the CHANGELOG can be ignored, as some of the items are still being worked on, namely, the rclone direct connections to debrid services and mergerfs. 🛠️
4. In its current form, the release will allow for existing functionality - running all the services in their form, but may not support some of the advanced options shown in the dmb_config.json, such as changing ports or other settings ✅
5. The default settings within the dmb_config.json is to run all services the first time DMB is deployed. 🤞
6. The default dmb_config.json can be found on the repo under the utils directory. 👀
7. The default dmb_config.json will be copied to the /config directory if it doesn't already exist; this means if you royally screw the pooch, you can delete the dmb_config.json and a new one will be provided at the next startup. 🤷‍♂️
8. Be cautious when making changes in the dmb_config.json; there are settings exposed that, if not properly defined, will cause issues.  Refer to # 7 in that event. 👆
9. Please report issues in this channel in a detailed manner - e.g., provide logs, details of what you were trying to accomplish, etc. Not, it's broke 🤣
10. Have fun and enjoy! 🎉
```
Example compose is as below:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:FastAPI                                      ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0 
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    shm_size: 128mb                                                  ## Increased for PostgreSQL     
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t    
    volumes:   
      - /home/username/docker/DMB/config:/config                     ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /home/username/docker/DMB/log:/log                           ## Location for logs
      - /home/username/docker/DMB/Zurg/RD:/zurg/RD                   ## Location for Zurg RealDebrid active configuration  
      - /home/username/docker/DMB/Zurg/mnt:/data:shared              ## Location for rclone mount to host
      - /home/username/docker/DMB/Riven/data:/riven/backend/data     ## Location for Riven backend data
      - /home/username/docker/DMB/Riven/mnt:/mnt                     ## Location for Riven symlinks
      - /home/username/docker/DMB/PostgreSQL/data:/postgres_data     ## Location for PostgreSQL database
      - /home/username/docker/DMB/pgAdmin4/data:/pgadmin/data        ## Location for pgAdmin 4 data
      - /home/username/docker/DMB/Zilean/data:/zilean/app/data       ## Location for Zilean data
    environment:
      - TZ=
      - PUID=
      - PGID=
      - DMB_LOG_LEVEL=DEBUG      
      - ZURG_INSTANCES_REALDEBRID_API_KEY=
      - ORIGIN=http://0.0.0.0:3000                                  ## See Riven documentation for more details
    # network_mode: container:gluetun                               ## Example to attach to gluetun vpn container if realdebrid blocks IP address 
    ports:
      - "3005:3005"                                                 ## DMB Frontend
      - "3000:3000"                                                 ## Riven Frontend
      - "5050:5050"                                                 ## pgAdmin 4
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
```

If you want to use the sponsored Zurg repo, add the below to the compose:
```
      - DMB_GITHUB_TOKEN=   
      - ZURG_INSTANCES_REALDEBRID_REPO_NAME=zurg
```
