### ISSUE TITLE
Riven's Frontend and backend process not starting

### ISSUE THREAD

**Issue by GSKang94** [I-am-PUID-0/DMB#13]
Hey Thanks for this amazing project 👏🏼 
I'm getting this error `ERROR - The Riven frontend process is not running. | The Riven backend process is not running.| The Rclone RD process for DMB is not running.`

Full log
```txt
Setting up Zurg
Jun 28, 2024 14:55:48 - INFO - Setting up Zurg w/ RealDebrid instance in directory: /zurg/RD/
Jun 28, 2024 14:55:48 - INFO - Found Zurg version v0.9.3-hotfix.11 in /zurg/RD/
Jun 28, 2024 14:55:48 - INFO - Preparing Zurg instance for RealDebrid
Jun 28, 2024 14:55:48 - INFO - Using Zurg app found for RealDebrid in /zurg/RD/
Jun 28, 2024 14:55:48 - INFO - Using Zurg config found for RealDebrid in /zurg/RD/
Jun 28, 2024 14:55:48 - INFO - Zurg setup process complete
Jun 28, 2024 14:55:48 - INFO - Automatic updates set to 24 hours for Zurg
Jun 28, 2024 14:55:48 - INFO - Fetching latest Zurg release.
Jun 28, 2024 14:55:48 - INFO - Starting Zurg w/ RealDebrid
Jun 28, 2024 14:55:48 - INFO - Checking rclone flags
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: Logging to logs/zurg-2024-06-28.log
Jun 28, 2024 14:55:48 - INFO - Configuring the rclone mount name to "DMB"
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	Version: v0.9.3-hotfix.11
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	GitCommit: 36298dd97973efd60dcf6caa70e1b6cc4145bcb7
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	BuiltAt: 2024-02-18T03:16:05
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	Debug logging is enabled; if you are not debugging please set LOG_LEVEL=info in your environment
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	Starting server on [::]:9362
Jun 28, 2024 14:55:48 - INFO - Configuring rclone for DMB
Jun 28, 2024 14:55:48 - INFO - Starting rclone for DMB
Jun 28, 2024 14:55:48 - INFO - rclone startup complete
Jun 28, 2024 14:55:48 - INFO - Configuring Riven
Jun 28, 2024 14:55:48 - INFO - Zurg latest release: v0.9.3-hotfix.11
Jun 28, 2024 14:55:48 - INFO - Zurg current version: v0.9.3-hotfix.11
Jun 28, 2024 14:55:48 - INFO - Zurg is already up to date.
Jun 28, 2024 14:55:48 - INFO - Zurg w/ RealDebrid subprocess: 	zurg	Your account will expire in 145 days
Jun 28, 2024 14:55:49 - INFO - Setting up Riven frontend
Jun 28, 2024 14:55:50 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Fetched info for 402 torrents
Jun 28, 2024 14:55:50 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Compiled into 400 torrents, 0 were missing info
Jun 28, 2024 14:55:50 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Starting periodic repair job
Jun 28, 2024 14:55:50 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Periodic repair started; searching for broken torrents
Jun 28, 2024 14:55:50 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Finished repairing 0 broken torrents
Jun 28, 2024 14:55:50 - INFO - Zurg w/ RealDebrid subprocess: 	manager	Starting periodic refresh job
Jun 28, 2024 14:56:58 - ERROR - The Riven frontend process is not running. | The Riven backend process is not running.| The Rclone RD process for DMB is not running.

```

My docker compose file
```yml
version: "3.8"
services:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest
    stdin_open: true
    tty: true
    volumes:
      - /home/DMB/config:/config
      - /home/DMB/log:/log
      - /home/DMB/Zurg/RD:/zurg/RD
      - /home/DMB/Zurg/mnt:/data:shared
      - /home/DMB/Riven/data:/riven/data
      - /home/DMB/Riven/mnt:/mnt
    environment:
      - TZ=xxxxx
      - ZURG_ENABLED=true
      - RD_API_KEY=xxxx
      - ZURG_UPDATE=true
      - RCLONE_MOUNT_NAME=DMB
      - RIVEN_ENABLED=true
      - ORIGIN=http://raspberrypi.local:3004
      - PLEX_TOKEN=xxxx
      - PLEX_ADDRESS=http://raspberrypi.local:32400
      - RIVEN_UPDATE=true
      - RIVEN_BRANCH=main
    ports:
      - 3004:3000
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
networks: {}

```
