### ISSUE TITLE
Cannot access riven dashboard after started

### ISSUE THREAD

**Issue by senshinya** [I-am-PUID-0/DMB#21]
**Describe the bug**

Cannot access riven dashboard after started

**Expected behavior**

Access riven dashboard normally

**Docker Compose**

```yaml
version: "3.8"
services:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest
    volumes:
      - /mnt/data/plex/DMB/config:/config
      - /mnt/data/plex/DMB/log:/log
      - /mnt/data/plex/zurg/RD:/zurg/RD
      - /mnt/data/plex/zurg/mnt:/data:shared
      - /mnt/data/plex/riven/data:/riven/backend/data
      - /mnt/data/plex/riven/mnt:/mnt
    environment:
      - TZ=Asia/Shanghai
      - ZURG_ENABLED=true
      - RD_API_KEY=xxxxxxxxx
      - RCLONE_MOUNT_NAME=real
      - RIVEN_BACKEND_ENABLED=true
      - RIVEN_FRONTEND_ENABLED=true
      - ORIGIN=https://192.168.6.148:30003
    ports:
      - 30003:3000
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
```

**Logs**

```
DMB  | Jul 26, 2024 10:53:22 - INFO - 
DMB  |                                                                        
DMB  | DDDDDDDDDDDDD        MMMMMMMM               MMMMMMMMBBBBBBBBBBBBBBBBB   
DMB  | D::::::::::::DDD     M:::::::M             M:::::::MB::::::::::::::::B  
DMB  | D:::::::::::::::DD   M::::::::M           M::::::::MB::::::BBBBBB:::::B 
DMB  | DDD:::::DDDDD:::::D  M:::::::::M         M:::::::::MBB:::::B     B:::::B
DMB  |   D:::::D    D:::::D M::::::::::M       M::::::::::M  B::::B     B:::::B
DMB  |   D:::::D     D:::::DM:::::::::::M     M:::::::::::M  B::::B     B:::::B
DMB  |   D:::::D     D:::::DM:::::::M::::M   M::::M:::::::M  B::::BBBBBB:::::B 
DMB  |   D:::::D     D:::::DM::::::M M::::M M::::M M::::::M  B:::::::::::::BB  
DMB  |   D:::::D     D:::::DM::::::M  M::::M::::M  M::::::M  B::::BBBBBB:::::B 
DMB  |   D:::::D     D:::::DM::::::M   M:::::::M   M::::::M  B::::B     B:::::B
DMB  |   D:::::D     D:::::DM::::::M    M:::::M    M::::::M  B::::B     B:::::B
DMB  |   D:::::D    D:::::D M::::::M     MMMMM     M::::::M  B::::B     B:::::B
DMB  | DDD:::::DDDDD:::::D  M::::::M               M::::::MBB:::::BBBBBB::::::B
DMB  | D:::::::::::::::DD   M::::::M               M::::::MB:::::::::::::::::B 
DMB  | D::::::::::::DDD     M::::::M               M::::::MB::::::::::::::::B  
DMB  | DDDDDDDDDDDDD        MMMMMMMM               MMMMMMMMBBBBBBBBBBBBBBBBB   
DMB  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
DMB  | 
DMB  |                               Version: 1.2.0                                    
DMB  | 
DMB  | 
DMB  | 
DMB  | Jul 26, 2024 10:53:22 - INFO - Setting up Zurg
DMB  | Jul 26, 2024 10:53:22 - INFO - Setting up Zurg w/ RealDebrid instance in directory: /zurg/RD/
DMB  | Jul 26, 2024 10:53:22 - INFO - Fetching latest Zurg release.
DMB  | Jul 26, 2024 10:53:23 - INFO - Zurg latest release: v0.9.3-final
DMB  | Jul 26, 2024 10:53:23 - INFO - Fetching release information from https://api.github.com/repos/debridmediamanager/zurg-testing/releases/tags/v0.9.3-final
DMB  | Jul 26, 2024 10:53:24 - INFO - Downloading from https://api.github.com/repos/debridmediamanager/zurg-testing/releases/assets/179496653
DMB  | Jul 26, 2024 10:53:27 - INFO - Successfully downloaded zurg-v0.9.3-final-linux-amd64 and extracted to zurg
DMB  | Jul 26, 2024 10:53:27 - INFO - Set permissions for zurg/zurg to 0o755
DMB  | Jul 26, 2024 10:53:27 - INFO - Preparing Zurg instance for RealDebrid
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg setup process complete
DMB  | Jul 26, 2024 10:53:27 - INFO - Automatic update disabled for Zurg
DMB  | Jul 26, 2024 10:53:27 - INFO - Starting Zurg w/ RealDebrid
DMB  | Jul 26, 2024 10:53:27 - INFO - Checking rclone flags
DMB  | Jul 26, 2024 10:53:27 - INFO - Configuring the rclone mount name to "real"
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg w/ RealDebrid subprocess: Logging to logs/zurg-2024-07-26.log
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg w/ RealDebrid subprocess:    zurg       Version: v0.9.3-final
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg w/ RealDebrid subprocess:    zurg       GitCommit: 4179c2745b4fb22fcb37f36de27b3daa39f114f0
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg w/ RealDebrid subprocess:    zurg       BuiltAt: 2024-07-14T09:48:30
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg w/ RealDebrid subprocess:    zurg       Debug logging is enabled; if you are not debugging please set LOG_LEVEL=info in your environment
DMB  | Jul 26, 2024 10:53:27 - INFO - Zurg w/ RealDebrid subprocess:    zurg       Starting server on [::]:9266
DMB  | Jul 26, 2024 10:53:28 - INFO - Configuring rclone for real
DMB  | Jul 26, 2024 10:53:28 - INFO - Waiting to start the rclone process until the Zurg WebDAV http://localhost:9266/dav/ is accessible.
DMB  | Jul 26, 2024 10:53:28 - INFO - The Zurg WebDAV URL http://localhost:9266/dav is accessible. Starting rclone daemon for real
DMB  | Jul 26, 2024 10:53:28 - INFO - rclone startup complete
DMB  | Jul 26, 2024 10:53:29 - INFO - Zurg w/ RealDebrid subprocess:    zurg       Your account will expire in 51 days
DMB  | Jul 26, 2024 10:53:39 - INFO - Zurg w/ RealDebrid subprocess:    manager    Fetched info for 44 torrents
DMB  | Jul 26, 2024 10:53:39 - INFO - Zurg w/ RealDebrid subprocess:    manager    Compiled into 44 torrents, 0 were missing info
DMB  | Jul 26, 2024 10:53:41 - INFO - Zurg w/ RealDebrid subprocess:    manager    Starting periodic repair job
DMB  | Jul 26, 2024 10:53:41 - INFO - Zurg w/ RealDebrid subprocess:    manager    Starting periodic refresh job
DMB  | Jul 26, 2024 10:53:41 - INFO - Zurg w/ RealDebrid subprocess:    manager    Periodic repair started; searching for broken torrents
DMB  | Jul 26, 2024 10:53:41 - INFO - Zurg w/ RealDebrid subprocess:    manager    Finished repairing 0 broken torrents
```

It seems after zurg finish initing, riven does not init
