### ISSUE TITLE
riven 500 | Internal error

### ISSUE THREAD

**Issue by vuongtt92** [I-am-PUID-0/DMB#35]
**Describe the bug**
hi, I'm trying to setup DMB with riven enabled. The front end has started sucessfully, I've gone through the initial setup but immediately after that it shows "500 | Internal error".
By checking the log, I see that the backend is trying to restart constantly but unsuccessful, the last error in the log is

```
24-08-22 11:37:52 | :x: ERROR     | program.validate_database - Database connection failed. Is the database running? 
24-08-22 11:46:59 |  CRITICAL  | main.<module> - Server has been stopped
```
Could anyone help? Thank you
here's my compose, could you pls. take a look to see what's wrong with it?
version: "3.8"

```
services:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    volumes:
      - /volume2/docker/dmb/config:/config
      ## Location for logs
      - /volume2/docker/dmb/log:/log
      - /volume2/docker/dmb/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - /volume2/docker/dmb/zurg/rd:/zurg/RD
      ## Location for rclone mount to host
      - /volume2/media/dmb/zurg/mnt:/data:shared 
      ## Location for Riven backend data
      - /volume2/docker/dmb/riven/data:/riven/backend/data
      ## Location for Riven symlinks
      - /volume2/media/dmb/riven/mnt:/mnt
    environment:
      - TZ=Asia/Saigon
      ## Zurg Required Settings
      - ZURG_ENABLED=true      
      - RD_API_KEY=Z7VDOS2OIEKH5DI3XXX
      ## Zurg Optional Settings
      - ZURG_UPDATE=true
        ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=DMB
      ## Rclone Optional Settings - See rclone docs for full list
      - ORIGIN=http://192.168.124.22:3000 # See Riven documentation for more details
      ## Riven Optional Settings
      - RIVEN_ENABLED=true
      - RIVEN_BACKEND_UPDATE=true
      - RIVEN_FRONTEND_UPDATE=true
      ## Special Features
      - DMB_LOG_LEVEL=DEBUG  # Master log level for all program logs in DMB
      - COLOR_LOG_ENABLED=true
    network_mode: bridge  
    ports:
      - "3000:3000"
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
```

**To Reproduce**
Access http://192.168.124.22:3000 and see the 500 | Internal error

**Expected behavior**

To be able to go to settings and setup riven via the Web UI.

**Please complete the following information:**
 - OS: DSM Synology SA6400
 - Version: 7.1
 - Supporting Applications: Docker (via Portainer)
