### ISSUE TITLE
Torrentio is broken -- Need host/port after enabling in Riven

### ISSUE THREAD

**Issue by profucius** [I-am-PUID-0/DMB#55]
New bug after closing #54 . I opened a ticket on the Riven repo directly for this one, and they referred me back to you/DMB again.

https://github.com/rivenmedia/riven/issues/722

Essentially the issue is that when I enable Torrentio in Riven settings, it crashes the Riven backend. Then when I restart the stack, it cannot load at all, and shuts down. When I asked for help, they said something about needing a host/port for it? I'm a bit confused.

I can modify and save other settings successfully, but when I enable Torrentio and save, this crashes.

**Comment by profucius** [comment]
> You know what Profucius says?
You got me there haha! Although normally I am adept at handling bugs, but with the combination of being newish with docker, and Riven making deep changes, I'm a bit turned around here.

I've attached the config files (tokens obfuscated) via a zip file in the link below, figured that is easier. Thanks for taking a look.

[profucius DMB configs.zip](https://github.com/user-attachments/files/17115858/profucius.DMB.configs.zip)

**Comment by NoSync** [comment]
Same issue for me. In fact, even after disabling torrentio manually from riven’s json settings, I get the same issue on startup and everything will eventually shut down - I’m not quite sure how to restore functionality.

I also tried a hard reset of Riven’s DB, but no luck.

**Comment by profucius** [comment]
This is what happens in the logs immediately after clicking Save after enabling Torrentio in Riven WebUI:

```
Sep 25, 2024 08:46:06 - ERROR - PostgreSQL subprocess: type "states" does not exist
Sep 25, 2024 08:46:06 - INFO - PostgreSQL subprocess: 2024-09-25 13:46:06.908 UTC [223] STATEMENT:  ALTER TABLE "MediaItem" ALTER COLUMN last_state TYPE states
Sep 25, 2024 08:46:06 - WARNING - riven_backend subprocess: | db.run_migrations - Error running migrations: (psycopg2.errors.UndefinedObject) type "states" does not exist
Sep 25, 2024 08:46:06 - INFO - riven_backend subprocess: [SQL: ALTER TABLE "MediaItem" ALTER COLUMN last_state TYPE states ]
Sep 25, 2024 08:46:06 - INFO - riven_backend subprocess: (Background on this error at: https://sqlalche.me/e/20/f405)
Sep 25, 2024 08:46:07 - INFO - riven_backend subprocess: Generating /riven/backend/data/alembic/2024_09_25_338ab47698b5_auto_upg_20240925084606.py ...  done
Sep 25, 2024 08:46:07 - ERROR - PostgreSQL subprocess: type "states" does not exist
Sep 25, 2024 08:46:07 - INFO - PostgreSQL subprocess: 2024-09-25 13:46:07.194 UTC [223] STATEMENT:  ALTER TABLE "MediaItem" ALTER COLUMN last_state TYPE states
Sep 25, 2024 08:46:07 - WARNING - riven_backend subprocess: | db.run_migrations - Error running migrations: (psycopg2.errors.UndefinedObject) type "states" does not exist
Sep 25, 2024 08:46:07 - INFO - riven_backend subprocess: [SQL: ALTER TABLE "MediaItem" ALTER COLUMN last_state TYPE states ]
Sep 25, 2024 08:46:07 - INFO - riven_backend subprocess: (Background on this error at: https://sqlalche.me/e/20/f405)
Sep 25, 2024 08:46:07 - INFO - riven_backend subprocess: Generating /riven/backend/data/alembic/2024_09_25_5df5b5413669_auto_upg_20240925084607.py ...  done
Sep 25, 2024 08:46:07 - CRITICAL - riven_backend subprocess: | main.<module> - Server has been stopped
Sep 25, 2024 08:46:08 - INFO - riven_backend subprocess: | 👾 API       | main.dispatch - GET /settings/load - 200 - 2.51s
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: TypeError: fetch failed
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: at node:internal/deps/undici/undici:12500:13
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: [cause]: Error: connect ECONNREFUSED 127.0.0.1:8080
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: errno: -111,
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: code: 'ECONNREFUSED',
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: syscall: 'connect',
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: address: '127.0.0.1',
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: port: 8080
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: }
Sep 25, 2024 08:46:08 - INFO - riven_frontend subprocess: }
```

And then in the Riven WebUI this shows:
![image](https://github.com/user-attachments/assets/08a93f06-4310-4ec9-a670-8136678188b7)

And then I refresh the page and this shows:
![image](https://github.com/user-attachments/assets/bcef3b46-3c59-4968-83f8-05e586c72625)

With only this in the log:
```
Sep 25, 2024 08:47:37 - INFO - riven_frontend subprocess: }
Sep 25, 2024 08:48:08 - ERROR - The Riven backend process is not running.
```

**Comment by profucius** [comment]
> Same issue for me. In fact, even after disabling torrentio manually from riven’s json settings, I get the same issue on startup and everything will eventually shut down - I’m not quite sure how to restore functionality.
> 
> I also tried a hard reset of Riven’s DB, but no luck.

This shouldn't be happening to you. I'm able to reverse it and get back into Riven again by simply changing this line to false in the Riven `settings.json` file, then restarting the stack (it takes about 3-5 minutes to fully boot)

```
        "torrentio": {
            "enabled": false,
```

**Comment by profucius** [comment]
> Try deleting the Riven/data/alembic directory and restarting.

I tried this and it did not work.

> As a last option, try deleting the PostgreSQL data directory and restarting.

Then I tried this, and it worked! Torrentio enabled successfully and Riven continued running. The downside is that I lost everything in the Library tab that Riven was tracking, but honestly that is a sacrifice I'm willing to make to get it running again.

Any idea how this might've happened? I'm currently assuming something went wrong with the recent Riven major changes.

**Comment by NoSync** [comment]
Something's even more odd on my side.

1. I made sure that torrentio is disabled in settings.json, and it is. Restarted, didn't help.
2. I zapped the alembic directory. Restarted, the directory is not recreated, didn't help.
3. I zapped the pgsql data directory. Restarted, the data directory is recreated, didn't help. 

Relevant part of the logs, for reference:

```
Sep 25, 2024 16:12:34 - INFO - Attempt 10/10 to fetch settings from http://127.0.0.1:8080/settings/get/all
Sep 25, 2024 16:12:34 - ERROR - Error fetching settings: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /settings/get/all (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f29379c3f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Sep 25, 2024 16:12:34 - ERROR - Max retries reached. Failed to fetch settings from http://127.0.0.1:8080/settings/get/all
Sep 25, 2024 16:12:34 - ERROR - Error loading Riven settings: No active exception to reraise
Sep 25, 2024 16:12:34 - ERROR - An error occurred in the Riven backend setup: No active exception to reraise
Sep 25, 2024 16:12:34 - INFO - Shutdown signal received. Cleaning up...
Sep 25, 2024 16:12:34 - INFO - Stopping riven_frontend
Sep 25, 2024 16:12:34 - WARNING - riven_frontend process not found or already stopped.
Sep 25, 2024 16:12:34 - INFO - Stopping riven_backend
Sep 25, 2024 16:12:34 - INFO - riven_backend process terminated gracefully.
```

And this is the relevant part of my docker compose:

```
services:
  dmb:
    image: iampuid0/dmb:latest
    container_name: dmb
    restart: unless-stopped
    stop_grace_period: 60s
    stdin_open: true
    tty: true
    volumes:
      - /home/nosync/media/dmb/config:/config:rw
      - /home/nosync/media/dmb/log:/log:rw
      - /home/nosync/media/dmb/zurg/RD:/zurg/RD:rw 
      - /home/nosync/media/dmb/zurg/mnt:/data:rshared
      - /home/nosync/media/dmb/riven/data:/riven/backend/data:rw
      - /home/nosync/media/dmb/riven/mnt:/mnt:rw
      - /home/nosync/media/dmb/pgsql/data:/postgres_data:rw
      ## Location for rclone cache if enabled
      - /data/cache/rclone:/cache:rw
      - /home/nosync/media/dmb/zilean/data:/zilean/app/data:rw
    environment:
      - TZ=Europe/Zurich
      - PUID=1000
      - PGID=1000
      - ZURG_ENABLED=true
      - ZURG_UPDATE=true
      - ZURG_LOG_LEVEL=info
      - RD_API_KEY=redacted
      - RCLONE_MOUNT_NAME=dmb
      - RCLONE_DIR_CACHE_TIME=10s
      - RCLONE_CACHE_DIR=/cache
      - RCLONE_VFS_READ_CHUNK_SIZE=1M
      - RCLONE_VFS_READ_CHUNK_SIZE_LIMIT=32M
      - RIVEN_ENABLED=true
      - RIVEN_BACKEND_UPDATE=true
      - RIVEN_FRONTEND_UPDATE=true
      - RIVEN_LOG_LEVEL=info
      - FRONTEND_LOGS=off
      - ORIGIN=https://redacted.proxy.com      
      - PLEX_TOKEN=redacted
      - PLEX_ADDRESS=https://redacted2.proxy.com
      - DUPLICATE_CLEANUP=true
      - CLEANUP_INTERVAL=24
      - SEERR_API_KEY=redacted
      - SEERR_ADDRESS=https://redacted3.proxy.com
      - ZILEAN_ENABLED=true
      - ZILEAN_UPDATE=true
      - DMB_LOG_LEVEL=info
      - COLOR_LOG_ENABLED=true
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
    healthcheck:
      start_period: 1m
      interval: 10s
      retries: 3
    networks:
      macvlan-docker:
        ipv4_address: 192.168.50.245
```
