### ISSUE TITLE
Overseerr not working with Riven

### ISSUE THREAD

**Issue by KodeStar** [I-am-PUID-0/DMB#64]
**Describe the bug**

I'm using docker compose on Unraid and currently have 2 stacks running, the first has just zurg, the other has Riven and Zilean.

```
services:
  DMB:
    container_name: Zurg
    image: iampuid0/dmb:latest                                       ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0 
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t    
    volumes:   
      - /mnt/user/appdata/DMB/config:/config                     ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /mnt/user/appdata/DMB/log:/log                           ## Location for logs
      - /mnt/user/appdata/DMB/cache:/cache
      - /mnt/user/appdata/DMB/Zurg/RD:/zurg/RD                   ## Location for Zurg RealDebrid active configuration  
      - /mnt/user/appdata/DMB/Zurg/AD:/zurg/AD
      - /mnt/user/appdata/DMB/Zurg/mnt:/data:shared              ## Location for rclone mount to host
    environment:
      - TZ=Europe/London
      - PUID=99
      - PGID=100
      - ZURG_ENABLED=true      
      - RD_API_KEY=MYAPIKEYISHERE
      - RCLONE_MOUNT_NAME=DMB
    # network_mode: container:gluetun                               ## Example to attach to gluetun vpn container if realdebrid blocks IP address
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
```
And
```
services:
  DMB:
    container_name: Riven
    image: iampuid0/dmb:latest                                       ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0 
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t    
    volumes:   
      - /mnt/user/appdata/DMB/config:/config                     ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /mnt/user/appdata/DMB/log:/log                           ## Location for logs
      - /mnt/user/appdata/DMB/Riven/data:/riven/backend/data     ## Location for Riven backend data
      - /mnt/user/appdata/DMB/Riven/mnt:/mnt                     ## Location for Riven symlinks
      - /mnt/user/appdata/DMB/PostgreSQL/data:/postgres_data     ## Location for PostgreSQL database
      - /mnt/user/appdata/DMB/Zilean/data:/zilean/app/data       ## Location for Zilean data
      - /mnt/user/appdata/DMB/Zurg/mnt:/data
    environment:
      - TZ=Europe/London
      - PUID=99
      - PGID=100
      - ZILEAN_ENABLED=true
      - RIVEN_ENABLED=true
      - RCLONE_MOUNT_NAME=DMB
      - ORIGIN=http://192.168.0.10:3000                                  ## See Riven documentation for more details
    # network_mode: container:gluetun                               ## Example to attach to gluetun vpn container if realdebrid blocks IP address 
    ports:
      - "3000:3000"                                                 ## Riven frontend
```

Requesting anything on Overseerr ends up with the following in the Riven logs:

```
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: SvelteKitError: POST method not allowed. No actions exist for this page
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: at handle_action_json_request (file:///riven/frontend/build/server/index.js:757:30)
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: at render_page (file:///riven/frontend/build/server/index.js:2388:12)
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: at async resolve2 (file:///riven/frontend/build/server/index.js:3513:24) {
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: status: 405,
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: text: 'Method Not Allowed'
Oct 19, 2024 20:59:48 - INFO - riven_frontend subprocess: }
```

Trying to test the webhook in Overseerr also fails.

<img width="376" alt="image" src="https://github.com/user-attachments/assets/cb192d3f-4a84-495c-82c1-2cb84787caa3">

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/1764a036-3c71-4451-8c10-b3f46e1fa9a8">

 - OS: Unraid
 - Version: 6.12.3
 - Supporting Applications: Docker / DMB

Any ideas?
