### ISSUE TITLE
cannot access local variable 'rd_port' when trying to use All Debrid

### ISSUE THREAD

**Issue by titooo7** [I-am-PUID-0/DMB#92]
I'm following the [wiki setup guide](https://github.com/I-am-PUID-0/DMB/wiki/Setup-Guides)  with very minor changes:
1- I changed some volumes paths and added the line '- /mnt/DMB/Zurg/RD:/zurg/AD' as I'm using all debrid so I thought I should
2- I changed  the line RD_API_KEY with AD_API_KEY because I'm using alldebrid so I thought I should.

Here is my docker-compose.yml file:

```
services:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest                                       ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0 
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t    
    volumes:   
      - /opt/DMB/config:/config                    
      - /opt/DMB/log:/log                           
      - /mnt/DMB/Zurg/RD:/zurg/RD 
      - /mnt/DMB/Zurg/AD:/zurg/AD
      - /mnt/DMB/Zurg/mnt:/data:shared 
      - /mnt/DMB/Riven/data:/riven/backend/data
      - /mnt/DMB/Riven/mnt:/mnt
      - /opt/DMB/PostgreSQL/data:/postgres_data 
      - /opt/DMB/pgAdmin4/data:/pgadmin/data
      - /opt/DMB/Zilean/data:/zilean/app/data
    environment:
      - TZ=
      - PUID=
      - PGID=
      - ZURG_ENABLED=true      
      - AD_API_KEY=my-all-debrid-key
      - RCLONE_MOUNT_NAME=DMB
      - ZILEAN_ENABLED=true
      - RIVEN_ENABLED=true
      - ORIGIN=http://my-server-ip-address:3000
      - PGADMIN_SETUP_EMAIL=
      - PGADMIN_SETUP_PASSWORD=
    # network_mode: container:gluetun                               ## Example to attach to gluetun vpn container if realdebrid blocks IP address 
    ports:
      - "3000:3000"
      - "5050:5050"
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
```

This is the error I get:
```

Version: 5.4.5                                                                                               
Dec  4, 2024 15:08:38 - INFO - Setting up Zurg                                                                                                                         
Dec  4, 2024 15:08:38 - INFO - Setting up Zurg w/ AllDebrid instance in directory: /zurg/AD/                                                                           
Dec  4, 2024 15:08:40 - INFO - Preparing Zurg instance for AllDebrid                                                                                                   
Dec  4, 2024 15:08:40 - INFO - Using Zurg config found for AllDebrid in /zurg/AD/                                                                                      
Dec  4, 2024 15:08:40 - INFO - Zurg setup process complete                                                                                                             
Dec  4, 2024 15:08:40 - INFO - Automatic update disabled for Zurg                                                                                                      
Dec  4, 2024 15:08:40 - INFO - Starting Zurg w/ AllDebrid process                                                                                                      
Dec  4, 2024 15:08:40 - INFO - Zurg process started with PID: 63                                                                                                       
Dec  4, 2024 15:08:40 - INFO - Checking rclone flags                                                                                                                   
Dec  4, 2024 15:08:40 - INFO - Configuring the rclone mount name to "DMB"                                                                                              
Dec  4, 2024 15:08:40 - INFO - Zurg w/ AllDebrid subprocess: Logging to logs/zurg-2024-12-04.log                                                                       
Dec  4, 2024 15:08:40 - INFO - Configuring rclone for DMB                                                                                                              
Dec  4, 2024 15:08:40 - ERROR - cannot access local variable 'rd_port' where it is not associated with a value           
```
